development:
  dialect: postgres
  database: rmuse_development
  user: the-hawk
  password: firebrand
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: rmuse_test
  user: the-hawk
  password: firebrand
  host: 127.0.0.1
  pool: 5

production:
  url: {{envOr "DATABASE_URL" "postgres://fail:morefail@127.0.0.1:5432/rmuse_production?sslmode=disable"}}